### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by djjudas21**
Add a `Dockerfile` and an `entrypoint.sh` to enable this to run inside a Docker container.

This has been tested and I am already using it after installing into Kubernetes via Helm:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: google-compute-snapshot
spec:
  schedule: "05 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: google-compute-snapshot
            image: djjudas21/google-compute-snapshot:docker_support
            imagePullPolicy: Always
            env:
            - name: "FILTER"
              value: "labels.auto_snapshot=true"
```

And this produces output like:

```
$ kubectl get all
NAME                                           READY   STATUS             RESTARTS   AGE
pod/google-compute-snapshot-1544544300-tnxvb   0/1     Completed          0          3m40s

NAME                                           COMPLETIONS   DURATION   AGE
job.batch/google-compute-snapshot-1544544300   1/1           23s        3m41s

NAME                                    SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/google-compute-snapshot   05 16 * * *   False     1        3m45s           154m
```

At the moment the Docker image is automagically built via [Docker Hub automated builds](https://hub.docker.com/r/djjudas21/google-compute-snapshot/) from my Github fork of this project. As part of this PR, please would you consider also setting up automated builds from your repo? I'm happy to explain this if you're not sure.

### CODE REVIEW

**Comment by jacksegal** [comment]
Thanks for the PR @djjudas21 - looks great - I'll take a proper look at it next week.

I haven't done anything with Docker Hub before, but have a stab at it - if I run into any problems, I'll give you a shout - appreciate the offer of help.

Jack

**Comment by martibutler** [comment]
This looks wonderful!!!!!

**Comment by djjudas21** [comment]
Happy new year! Don't suppose you've had a chance to look at this yet? Thanks :smile:

**Comment by jacksegal** [comment]
Happy new year to you too!  Thanks for your reminder - I've merged it into the master branch and have opened an issue for me to do the Docker hub - will take a look at that now.

Thanks for the PR!

**Pull request merged**
